---
- name: Build tor-snowflake
  docker_image:
    build:
      path: ./files/tor-snowflake
    name: "{{ anticECR.repository.repositoryUri }}"
    tag: "tor-snowflake"
    push: True
    source: build

- name: Build signal-proxy
  docker_image:
    build:
      path: ./files/signal-proxy/nginx-relay
    name: "{{ anticECR.repository.repositoryUri }}"
    tag: "signal-proxy"
    push: True
    source: build